export const categoryMap = {
  gen: "general",
  general: "general",
  obc: "obc",
  "obc-ncl": "obc",
  obcncl: "obc",
  sc: "sc",
  st: "st",
  ews: "ews",
  "ews-ncl": "ews",
  ewsc: "ews",
  "general-pwd": "generalPwD",
  "gen-pwd": "generalPwD",
  "obc-pwd": "obcPwD",
  "obc-ncl-pwd": "obcPwD",
  "obcncl-pwd": "obcPwD",
  "sc-pwd": "scPwD",
  "st-pwd": "stPwD",
  "ews-pwd": "ewsPwD",
  "ews-ncl-pwd": "ewsPwD",
  preparatory: "preparatory",
  "gen-ews": "ews",
};
