export const searchData = [
  { path: "/", title: "Home" },
  { path: "/admin/dashboard", title: "Admin Dashboard" },
  { path: "/admin/batch", title: "Admin Batch Management" },
  { path: "/admin/academic", title: "Academic Management" },
  { path: "/admin/users", title: "User Master" },
  { path: "/admin/books", title: "Admin Books Management" },
  { path: "/admin/exams/online", title: "Admin Online Exams" },
  { path: "/admin/exams/offline", title: "Admin Offline Exams" },
  { path: "/admin/jee-data", title: "JEE Data" },
  { path: "/admin/batch", title: "Batch Management" },
  { path: "/admin/lectures", title: "Admin Lectures" },
  { path: "/lectures", title: "Lectures" },
  { path: "/batch", title: "Batch List" },
  { path: "/batch/:id", title: "Batch Details" },
  { path: "/profile", title: "User Profile" },
  { path: "/doubts", title: "Doubts" },
  { path: "/chat", title: "Chat" },
  { path: "/question-bank", title: "Question Bank" },
  { path: "/test", title: "Test Page" },
  { path: "/automation/jeemaincityinfo", title: "JEE Main City Info" },
  { path: "/automation/jeemainadmitcard", title: "JEE Main Admit Card" },
  { path: "/automation/jdstadmitcard", title: "Generate Admit Card" },
  { path: "/exams/online", title: "Online Exam" },
  { path: "/exams/offline", title: "Offline Exam" },
  { path: "/analysis/jeemain", title: "JEE Main Analysis" },
  { path: "/analysis/jeeadvanced", title: "JEE Advanced Analysis" },
  { path: "/automation/jee/cityinfo", title: "Automation - JEE City Info" },
  { path: "/automation/jee/admitcard", title: "Automation - JEE Admit Card" },
  { path: "/admin/exams/offline", title: "Offline Exams" },
  { path: "/admin/exams/online", title: "Online Exams" },
  { path: "/analysis/jeemain", title: "JEE Main Analysis" },
  { path: "/analysis/jeeadvanced", title: "JEE Advanced Analysis" },
];
